DROP TABLE IF EXISTS public.cprd_lookup;
CREATE TABLE public.cprd_lookup (
  lookup_type CHAR(3),
  lookup_name TEXT,
  code        TEXT,
  description TEXT
);

INSERT INTO public.cprd_lookup
VALUES
  ('AAR', 'Asthma Risk Factors', '0', 'Data Not Entered'),
  ('AAR', 'Asthma Risk Factors', '1', 'Not at risk'),
  ('AAR', 'Asthma Risk Factors', '2', 'Previous history of severe attack'),
  ('AAR', 'Asthma Risk Factors', '3', 'On 3 or more drugs'),
  ('AAR', 'Asthma Risk Factors', '4', 'Night symptoms'),
  ('AAR', 'Asthma Risk Factors', '5', 'Recent hospital admission'),
  ('AAR', 'Asthma Risk Factors', '6', 'Other reason'),
  ('ABO', 'Blood Group', '0', 'Data Not Entered'),
  ('ABO', 'Blood Group', '1', 'A'),
  ('ABO', 'Blood Group', '2', 'A+'),
  ('ABO', 'Blood Group', '3', 'A-'),
  ('ABO', 'Blood Group', '4', 'B'),
  ('ABO', 'Blood Group', '5', 'B+'),
  ('ABO', 'Blood Group', '6', 'B-'),
  ('ABO', 'Blood Group', '7', 'O'),
  ('ABO', 'Blood Group', '8', 'O+'),
  ('ABO', 'Blood Group', '9', 'O-'),
  ('ABO', 'Blood Group', '10', 'AB'),
  ('ABO', 'Blood Group', '11', 'AB+'),
  ('ABO', 'Blood Group', '12', 'AB-'),
  ('ABO', 'Blood Group', '13', 'Rhesus +'),
  ('ABO', 'Blood Group', '14', 'Rhesus -'),
  ('ADT', 'Advice Type', '0', 'Data Not Entered'),
  ('ADT', 'Advice Type', '1', 'Alcohol'),
  ('ADT', 'Advice Type', '2', 'Smoking'),
  ('ADT', 'Advice Type', '3', 'Diet'),
  ('ADT', 'Advice Type', '4', 'Family History'),
  ('ADT', 'Advice Type', '5', 'Breast self examination'),
  ('ADT', 'Advice Type', '6', 'Testes self-examination'),
  ('ADT', 'Advice Type', '7', 'Menopause counselling'),
  ('ADT', 'Advice Type', '8', 'Risk of CVD'),
  ('ADT', 'Advice Type', '9', 'Exercise'),
  ('ADV', 'Advice Given', '0', 'Data Not Entered'),
  ('ADV', 'Advice Given', '1', 'Advice'),
  ('ADV', 'Advice Given', '2', 'Leaflet and advice'),
  ('ADV', 'Advice Given', '3', 'Internal counselling'),
  ('ADV', 'Advice Given', '4', 'External counselling'),
  ('ADV', 'Advice Given', '5', 'Therapy'),
  ('ADV', 'Advice Given', '6', 'PILS Leaflets'),
  ('AFD', 'After Death', '0', 'Data Not Entered'),
  ('AFD', 'After Death', '1', 'Seen after death by me'),
  ('AFD', 'After Death', '2', 'Seen after death by another medical practitioner'),
  ('AFD', 'After Death', '3', 'Not seen after death by a medical practitioner'),
  ('AGC', 'Elderly Patient Agencies', '0', 'Data Not Entered'),
  ('AGC', 'Elderly Patient Agencies', '1', 'Meals on wheels'),
  ('AGC', 'Elderly Patient Agencies', '2', 'District Nurse'),
  ('AGC', 'Elderly Patient Agencies', '3', 'Social services'),
  ('AGC', 'Elderly Patient Agencies', '4', 'Home help'),
  ('AGC', 'Elderly Patient Agencies', '5', 'Other'),
  ('AGC', 'Elderly Patient Agencies', '6', 'Health Visitor'),
  ('AMA', 'Asthma Management', '0', 'Data Not Entered'),
  ('AMA', 'Asthma Management', '1', 'Start inhaled steroids'),
  ('AMA', 'Asthma Management', '2', 'Double inhaled steroids'),
  ('AMA', 'Asthma Management', '3', 'Start oral steroids'),
  ('AMA', 'Asthma Management', '4', 'Call Doctor'),
  ('ASL', 'Asleep', '0', 'Data Not Entered'),
  ('ASL', 'Asleep', '1', 'Asleep'),
  ('ASL', 'Asleep', '2', 'Awake'),
  ('ASL', 'Asleep', '3', 'Asleep and awake'),
  ('ATT', 'Attendance Type', '0', 'Data Not Entered'),
  ('ATT', 'Attendance Type', '1', 'First visit'),
  ('ATT', 'Attendance Type', '2', 'Subsequent visit'),
  ('ATT', 'Attendance Type', '3', 'Last visit'),
  ('ATT', 'Attendance Type', '4', 'First follow-up'),
  ('ATT', 'Attendance Type', '5', 'Subsequent follow-up'),
  ('BMO', 'Birth Mode', '0', 'Data Not Entered'),
  ('BMO', 'Birth Mode', '1', 'Normal'),
  ('BMO', 'Birth Mode', '2', 'Forceps'),
  ('BMO', 'Birth Mode', '3', 'Ventouse'),
  ('BMO', 'Birth Mode', '4', 'Caesarian'),
  ('BMO', 'Birth Mode', '5', 'Unknown'),
  ('BPR', 'Birth Presentation', '0', 'Data Not Entered'),
  ('BPR', 'Birth Presentation', '1', 'Vertex'),
  ('BPR', 'Birth Presentation', '2', 'Breech'),
  ('BPR', 'Birth Presentation', '3', 'Transverse lie'),
  ('BPR', 'Birth Presentation', '4', 'Other'),
  ('BPR', 'Birth Presentation', '5', 'Unknown'),
  ('CAP', 'Capitation Supplement', '0', 'Data Not Entered'),
  ('CAP', 'Capitation Supplement', '1', 'Low'),
  ('CAP', 'Capitation Supplement', '2', 'Medium'),
  ('CAP', 'Capitation Supplement', '3', 'High'),
  ('CAP', 'Capitation Supplement', '4', 'Not Applicable'),
  ('CEN', 'Centiles', '0', 'Data Not Entered'),
  ('CEN', 'Centiles', '1', '< 3'),
  ('CEN', 'Centiles', '2', '3 - 9'),
  ('CEN', 'Centiles', '3', '10 - 24'),
  ('CEN', 'Centiles', '4', '25 - 49'),
  ('CEN', 'Centiles', '5', '50 - 74'),
  ('CEN', 'Centiles', '6', '75 - 89'),
  ('CEN', 'Centiles', '7', '90 - 97'),
  ('CEN', 'Centiles', '8', '> 97'),
  ('CER', 'Certainty', '0', 'Data Not Entered'),
  ('CER', 'Certainty', '1', 'Tentative'),
  ('CER', 'Certainty', '2', 'Unlikely'),
  ('CER', 'Certainty', '3', 'Possible'),
  ('CER', 'Certainty', '4', 'Likely'),
  ('CER', 'Certainty', '5', 'Certain'),
  ('CER', 'Certainty', '6', 'Absolute'),
  ('CHS', 'Chs Stages', '0', 'Data Not Entered'),
  ('CHS', 'Chs Stages', '1', 'Birth'),
  ('CHS', 'Chs Stages', '2', '6 weeks'),
  ('CHS', 'Chs Stages', '3', '8 months'),
  ('CHS', 'Chs Stages', '4', '18 months'),
  ('CHS', 'Chs Stages', '5', '3 years'),
  ('CHS', 'Chs Stages', '6', '4+ years'),
  ('COD', 'Category Of Death', '0', 'Data Not Entered'),
  ('COD', 'Category Of Death', '1', 'Category Ia'),
  ('COD', 'Category Of Death', '2', 'Category Ib'),
  ('COD', 'Category Of Death', '3', 'Category Ic'),
  ('COD', 'Category Of Death', '4', 'Category II'),
  ('COS', 'Type Of Consent', '0', 'Data Not Entered'),
  ('COS', 'Type Of Consent', '1', 'Full consent'),
  ('COS', 'Type Of Consent', '2', 'Partial consent'),
  ('COS', 'Type Of Consent', '3', 'No consent'),
  ('COT', 'Consultation Type', '0', 'Data Not Entered'),
  ('COT', 'Consultation Type', '1', 'Clinic'),
  ('COT', 'Consultation Type', '2', 'Night visit, Deputising service'),
  ('COT', 'Consultation Type', '3', 'Follow-up/routine visit'),
  ('COT', 'Consultation Type', '4', 'Night visit, Local rota'),
  ('COT', 'Consultation Type', '5', 'Mail from patient'),
  ('COT', 'Consultation Type', '6', 'Night visit , practice'),
  ('COT', 'Consultation Type', '7', 'Out of hours, Practice'),
  ('COT', 'Consultation Type', '8', 'Out of hours, Non Practice'),
  ('COT', 'Consultation Type', '9', 'Surgery consultation'),
  ('COT', 'Consultation Type', '10', 'Telephone call from a patient'),
  ('COT', 'Consultation Type', '11', 'Acute visit'),
  ('COT', 'Consultation Type', '12', 'Discharge details'),
  ('COT', 'Consultation Type', '13', 'Letter from Outpatients'),
  ('COT', 'Consultation Type', '14', 'Repeat Issue'),
  ('COT', 'Consultation Type', '15', 'Other'),
  ('COT', 'Consultation Type', '16', 'Results recording'),
  ('COT', 'Consultation Type', '17', 'Mail to patient'),
  ('COT', 'Consultation Type', '18', 'Emergency Consultation'),
  ('COT', 'Consultation Type', '19', 'Administration'),
  ('COT', 'Consultation Type', '20', 'Casualty Attendance'),
  ('COT', 'Consultation Type', '21', 'Telephone call to a patient'),
  ('COT', 'Consultation Type', '22', 'Third Party Consultation'),
  ('COT', 'Consultation Type', '23', 'Hospital Admission'),
  ('COT', 'Consultation Type', '24', 'Children''s Home Visit'),
  ('COT', 'Consultation Type', '25', 'Day Case Report'),
  ('COT', 'Consultation Type', '26', 'GOS18 Report'),
  ('COT', 'Consultation Type', '27', 'Home Visit'),
  ('COT', 'Consultation Type', '28', 'Hotel Visit'),
  ('COT', 'Consultation Type', '29', 'NHS Direct Report'),
  ('COT', 'Consultation Type', '30', 'Nursing Home Visit'),
  ('COT', 'Consultation Type', '31', 'Residential Home Visit'),
  ('COT', 'Consultation Type', '32', 'Twilight Visit'),
  ('COT', 'Consultation Type', '33', 'Triage'),
  ('COT', 'Consultation Type', '34', 'Walk-in Centre'),
  ('COT', 'Consultation Type', '35', 'Co-op Telephone advice'),
  ('COT', 'Consultation Type', '36', 'Co-op Surgery Consultation'),
  ('COT', 'Consultation Type', '37', 'Co-op Home Visit'),
  ('COT', 'Consultation Type', '38', 'Minor Injury Service'),
  ('COT', 'Consultation Type', '39', 'Medicine Management'),
  ('COT', 'Consultation Type', '40', 'Community Clinic'),
  ('COT', 'Consultation Type', '41', 'Community Nursing Note'),
  ('COT', 'Consultation Type', '42', 'Community Nursing Report'),
  ('COT', 'Consultation Type', '43', 'Data Transferred from other system'),
  ('COT', 'Consultation Type', '44', 'Health Authority Entry'),
  ('COT', 'Consultation Type', '45', 'Health Visitor Note'),
  ('COT', 'Consultation Type', '46', 'Health Visitor Report'),
  ('COT', 'Consultation Type', '47', 'Hospital Inpatient Report'),
  ('COT', 'Consultation Type', '48', 'Initial Post Discharge Review'),
  ('COT', 'Consultation Type', '49', 'Laboratory Request'),
  ('COT', 'Consultation Type', '50', 'Night Visit'),
  ('COT', 'Consultation Type', '51', 'Radiology Request'),
  ('COT', 'Consultation Type', '52', 'Radiology Result'),
  ('COT', 'Consultation Type', '53', 'Referral Letter'),
  ('COT', 'Consultation Type', '54', 'Social Services Report'),
  ('COT', 'Consultation Type', '55', 'Telephone Consultation'),
  ('COT', 'Consultation Type', '56', 'Template Entry'),
  ('COT', 'Consultation Type', '57', 'GP to GP communication transaction'),
  ('COT', 'Consultation Type', '58', 'Non-consultation medication data'),
  ('COT', 'Consultation Type', '59', 'Non-consultation data'),
  ('COT', 'Consultation Type', '60', 'ePharmacy message'),
  ('CST', 'Current Status', '0', 'Data Not Entered'),
  ('CST', 'Current Status', '1', 'Observation only'),
  ('CST', 'Current Status', '2', 'Continuous treatment'),
  ('CST', 'Current Status', '3', 'Resolved'),
  ('CST', 'Current Status', '4', 'Intermittent treatment'),
  ('CTT', 'Contraceptive Service Type', '0', 'Data Not Entered'),
  ('CTT', 'Contraceptive Service Type', '1', 'First service'),
  ('CTT', 'Contraceptive Service Type', '2', 'Subsequent service'),
  ('CTT', 'Contraceptive Service Type', '3', 'Service end'),
  ('CUF', 'Cuff', '0', 'Data Not Entered'),
  ('CUF', 'Cuff', '1', 'Standard'),
  ('CUF', 'Cuff', '2', 'Paediatric'),
  ('CUF', 'Cuff', '3', 'Large'),
  ('CVD', 'Cvd Risk', '0', 'Data Not Entered'),
  ('CVD', 'Cvd Risk', '1', 'General Advice Only'),
  ('CVD', 'Cvd Risk', '2', 'Opportunistic Intervention'),
  ('CVD', 'Cvd Risk', '3', 'Priority'),
  ('CYX', 'Cervical Cytology Exclusion', '0', 'Data Not Entered'),
  ('CYX', 'Cervical Cytology Exclusion', '1', 'Hysterectomy'),
  ('CYX', 'Cervical Cytology Exclusion', '2', 'Follow-up Stopped'),
  ('CYX', 'Cervical Cytology Exclusion', '3', 'Patient refusal'),
  ('CYX', 'Cervical Cytology Exclusion', '4', 'Considered inappropriate'),
  ('DAS', 'Diagnosis Of Asthma', '0', 'Data Not Entered'),
  ('DAS', 'Diagnosis Of Asthma', '1', 'Chest symptoms'),
  ('DAS', 'Diagnosis Of Asthma', '2', 'Symptoms'),
  ('DAS', 'Diagnosis Of Asthma', '3', 'Night cough'),
  ('DAS', 'Diagnosis Of Asthma', '4', 'Peak flow variation > 15%'),
  ('DAS', 'Diagnosis Of Asthma', '5', 'Other'),
  ('DBS', 'Diabetic Status', '0', 'Data Not Entered'),
  ('DBS', 'Diabetic Status', '1', 'Oral hypoglycaemics'),
  ('DBS', 'Diabetic Status', '2', 'Using Insulin'),
  ('DBS', 'Diabetic Status', '3', 'Dietary control'),
  ('DBS', 'Diabetic Status', '4', 'Gestational'),
  ('DBS', 'Diabetic Status', '5', 'Other'),
  ('DBS', 'Diabetic Status', '6', 'Resolved'),
  ('DEP', 'Departments', '0', 'No Data Entered'),
  ('DEP', 'Departments', '1', 'General Surgery'),
  ('DEP', 'Departments', '2', 'Urology'),
  ('DEP', 'Departments', '3', 'Trauma and Orthopaedics'),
  ('DEP', 'Departments', '4', 'ENT'),
  ('DEP', 'Departments', '5', 'Ophthalmology'),
  ('DEP', 'Departments', '6', 'Oral Surgery'),
  ('DEP', 'Departments', '7', 'Restorative Dentistry'),
  ('DEP', 'Departments', '8', 'Paediatric Dentistry'),
  ('DEP', 'Departments', '9', 'Orthodontics'),
  ('DEP', 'Departments', '10', 'Neurosurgery'),
  ('DEP', 'Departments', '11', 'Plastic Surgery'),
  ('DEP', 'Departments', '12', 'Cardiothoracic Surgery'),
  ('DEP', 'Departments', '13', 'Paediatric Surgery'),
  ('DEP', 'Departments', '14', 'Accident and Emergency'),
  ('DEP', 'Departments', '15', 'Anaesthetics'),
  ('DEP', 'Departments', '16', 'General Medicine'),
  ('DEP', 'Departments', '17', 'Gastroenterology'),
  ('DEP', 'Departments', '18', 'Endocrinology'),
  ('DEP', 'Departments', '19', 'Haematology (Clinical)'),
  ('DEP', 'Departments', '20', 'Clinical Physiology'),
  ('DEP', 'Departments', '21', 'Clinical Pharmacology'),
  ('DEP', 'Departments', '22', 'Audiological Medicine'),
  ('DEP', 'Departments', '23', 'Clinical Genetics'),
  ('DEP', 'Departments', '24', 'Clinical Cytogenetics and Molecular Genetics'),
  ('DEP', 'Departments', '25', 'Clinical Immunology and Allergy'),
  ('DEP', 'Departments', '26', 'Rehabilitation'),
  ('DEP', 'Departments', '27', 'Palliative Medicine'),
  ('DEP', 'Departments', '28', 'Cardiology'),
  ('DEP', 'Departments', '29', 'Dermatology'),
  ('DEP', 'Departments', '30', 'Thoracic Medicine'),
  ('DEP', 'Departments', '31', 'Infectious Diseases'),
  ('DEP', 'Departments', '32', 'Genito-Urinary Medicine'),
  ('DEP', 'Departments', '33', 'Nephrology'),
  ('DEP', 'Departments', '34', 'Medical Oncology'),
  ('DEP', 'Departments', '35', 'Nuclear Medicine'),
  ('DEP', 'Departments', '36', 'Neurology'),
  ('DEP', 'Departments', '37', 'Clinical Neuro-Physiology'),
  ('DEP', 'Departments', '38', 'Rheumatology'),
  ('DEP', 'Departments', '39', 'Paediatrics'),
  ('DEP', 'Departments', '40', 'Paediatric Neurology'),
  ('DEP', 'Departments', '41', 'Geriatric Medicine'),
  ('DEP', 'Departments', '42', 'Dental Medicine Specialties'),
  ('DEP', 'Departments', '43', 'Obstetrics (Hospital Bed or Delivery Facilities)'),
  ('DEP', 'Departments', '44', 'Gynaecology'),
  ('DEP', 'Departments', '45', 'Ante-natal clinic'),
  ('DEP', 'Departments', '46', 'Post-natal clinic'),
  ('DEP', 'Departments', '47', 'Maternity Function'),
  ('DEP', 'Departments', '48', 'Other than Maternity'),
  ('DEP', 'Departments', '49', 'Mental Handicap'),
  ('DEP', 'Departments', '50', 'Mental Illness'),
  ('DEP', 'Departments', '51', 'Child and Adolescent Psychiatry'),
  ('DEP', 'Departments', '52', 'Forensic Psychiatry'),
  ('DEP', 'Departments', '53', 'Psychotherapy'),
  ('DEP', 'Departments', '54', 'Old Age Psychiatry'),
  ('DEP', 'Departments', '55', 'Clinical Oncology'),
  ('DEP', 'Departments', '56', 'Radiology'),
  ('DEP', 'Departments', '57', 'General Pathology'),
  ('DEP', 'Departments', '58', 'Blood Transfusion'),
  ('DEP', 'Departments', '59', 'Chemical Pathology'),
  ('DEP', 'Departments', '60', 'Haematology'),
  ('DEP', 'Departments', '61', 'Histopathology'),
  ('DEP', 'Departments', '62', 'Immunopathology'),
  ('DEP', 'Departments', '63', 'Medical Microbiology'),
  ('DEP', 'Departments', '64', 'Neuropathology'),
  ('DEP', 'Departments', '65', 'Community Medicine'),
  ('DEP', 'Departments', '66', 'Occupational Medicine'),
  ('DEP', 'Departments', '67', 'Joint Consultant Clinics'),
  ('DEP', 'Departments', '68', 'Clinical Psychology'),
  ('DEP', 'Departments', '69', 'Learning Disabilities'),
  ('DEP', 'Departments', '70', 'Adult Psychiatry'),
  ('DEP', 'Departments', '71', 'Community Paediatrics'),
  ('DEP', 'Departments', '72', 'Diabetic Nurse Specialist'),
  ('DEP', 'Departments', '73', 'Optometrist'),
  ('DEP', 'Departments', '74', 'Speech Therapy'),
  ('DEP', 'Departments', '75', 'Chiropody'),
  ('DEP', 'Departments', '76', 'Dietetics'),
  ('DEP', 'Departments', '77', 'Physiotherapy'),
  ('DEP', 'Departments', '78', 'Occupational Therapy'),
  ('DEP', 'Departments', '79', 'Community Psychiatric Nurse'),
  ('DEP', 'Departments', '80', 'Mobile Diabetic Eye Screening'),
  ('DEP', 'Departments', '81', 'Obstetrics & Gynaecology'),
  ('DEP', 'Departments', '82', 'Pain Management'),
  ('DEP', 'Departments', '83', 'Medical Ophthalmology'),
  ('DEP', 'Departments', '84', 'Midwife Episode'),
  ('DEP', 'Departments', '85', 'General Practice'),
  ('DEP', 'Departments', '86', 'Nursing Episode'),
  ('DEP', 'Departments', '87', 'Vascular Surgeons'),
  ('DEP', 'Departments', '88', 'Hearing Aid Clinic'),
  ('DEP', 'Departments', '89', 'Endodontics'),
  ('DEP', 'Departments', '90', 'Prosthodontics'),
  ('DEP', 'Departments', '91', 'Paediatric Cardiology'),
  ('DEP', 'Departments', '92', 'Tropical Medicine'),
  ('DEP', 'Departments', '93', 'Community Sexual and Reproductive Health'),
  ('DEP', 'Departments', '94', 'Public Health'),
  ('DIE', 'Type Of Diet', '0', 'Data Not Entered'),
  ('DIE', 'Type Of Diet', '1', 'Vegetarian'),
  ('DIE', 'Type Of Diet', '2', 'Vegan'),
  ('EPI', 'Episode Type', '0', 'Data Not Entered'),
  ('EPI', 'Episode Type', '1', 'First Ever'),
  ('EPI', 'Episode Type', '2', 'New event'),
  ('EPI', 'Episode Type', '3', 'Continuing'),
  ('EPI', 'Episode Type', '4', 'Other'),
  ('EPM', 'Epilepsy Management', '0', 'Data Not Entered'),
  ('EPM', 'Epilepsy Management', '1', 'Hospital only'),
  ('EPM', 'Epilepsy Management', '2', 'Community only'),
  ('EPM', 'Epilepsy Management', '3', 'GP only'),
  ('EPM', 'Epilepsy Management', '4', 'Shared'),
  ('EPM', 'Epilepsy Management', '5', 'Other'),
  ('EXE', 'Exercise', '0', 'Data Not Entered'),
  ('EXE', 'Exercise', '1', 'Inactive'),
  ('EXE', 'Exercise', '2', 'Moderate'),
  ('EXE', 'Exercise', '3', 'Vigorous'),
  ('EXE', 'Exercise', '4', 'Gentle'),
  ('FIT', 'Epileptic Fit Frequency', '0', 'Data Not Entered'),
  ('FIT', 'Epileptic Fit Frequency', '1', 'Daily'),
  ('FIT', 'Epileptic Fit Frequency', '2', 'Weekly'),
  ('FIT', 'Epileptic Fit Frequency', '3', 'Monthly'),
  ('FIT', 'Epileptic Fit Frequency', '4', 'Quarterly'),
  ('FIT', 'Epileptic Fit Frequency', '5', 'Yearly'),
  ('FIT', 'Epileptic Fit Frequency', '6', '> Daily'),
  ('FIT', 'Epileptic Fit Frequency', '7', '> Weekly'),
  ('FIT', 'Epileptic Fit Frequency', '8', '> Monthly'),
  ('FIT', 'Epileptic Fit Frequency', '9', '> Quarterly'),
  ('FIT', 'Epileptic Fit Frequency', '10', '> Yearly'),
  ('FIT', 'Epileptic Fit Frequency', '11', 'Less frequent'),
  ('FPR', 'Fetal Presentation', '0', 'Data Not Entered'),
  ('FPR', 'Fetal Presentation', '1', 'Cephalic'),
  ('FPR', 'Fetal Presentation', '2', 'Breech'),
  ('FPR', 'Fetal Presentation', '3', 'Transverse lie'),
  ('FPR', 'Fetal Presentation', '4', 'Oblique'),
  ('FPR', 'Fetal Presentation', '5', 'Unknown'),
  ('GLA', 'Visual Aids', '0', 'Data Not Entered'),
  ('GLA', 'Visual Aids', '1', 'Wears spectacles'),
  ('GLA', 'Visual Aids', '2', 'Wears contact lenses'),
  ('GLA', 'Visual Aids', '3', 'None'),
  ('GMP', 'Examination', '0', 'Data Not Entered'),
  ('GMP', 'Examination', '1', 'Good'),
  ('GMP', 'Examination', '2', 'Moderate'),
  ('GMP', 'Examination', '3', 'Poor'),
  ('GMP', 'Examination', '4', 'Not examined'),
  ('HPS', 'Program Type', '0', 'Data Not Entered'),
  ('HPS', 'Program Type', '1', 'Hospital'),
  ('HPS', 'Program Type', '2', 'Practice'),
  ('HPS', 'Program Type', '3', 'Shared'),
  ('IMC', 'Immunisation Compound', '0', 'Data Not Entered'),
  ('IMC', 'Immunisation Compound', '1', 'DT'),
  ('IMC', 'Immunisation Compound', '2', 'MMR'),
  ('IMC', 'Immunisation Compound', '3', 'DTP'),
  ('IMC', 'Immunisation Compound', '4', 'TD'),
  ('IMC', 'Immunisation Compound', '5', 'TP'),
  ('IMC', 'Immunisation Compound', '6', 'MR'),
  ('IMC', 'Immunisation Compound', '7', 'HIBDTP'),
  ('IMC', 'Immunisation Compound', '8', 'DP'),
  ('IMC', 'Immunisation Compound', '9', 'HEPABTWIN'),
  ('IMC', 'Immunisation Compound', '10', 'HEPATYP'),
  ('IMC', 'Immunisation Compound', '11', 'DTAPIPVHIB'),
  ('IMC', 'Immunisation Compound', '12', 'DTAPIPV'),
  ('IMC', 'Immunisation Compound', '13', 'DTIPV'),
  ('IMC', 'Immunisation Compound', '14', 'HEPATYP2'),
  ('IMC', 'Immunisation Compound', '15', 'HIBMENC'),
  ('IMC', 'Immunisation Compound', '16', 'HEPABAMBRIX'),
  ('IMC', 'Immunisation Compound', '17', 'HEPABAMBPA'),
  ('IMC', 'Immunisation Compound', '18', 'DTAP'),
  ('IMC', 'Immunisation Compound', '19', 'POLIO'),
  ('IMC', 'Immunisation Compound', '20', 'TETANUS'),
  ('IMC', 'Immunisation Compound', '21', 'MENC'),
  ('IMC', 'Immunisation Compound', '22', 'PERTUSSIS'),
  ('IMC', 'Immunisation Compound', '23', 'MUMPS'),
  ('IMC', 'Immunisation Compound', '24', 'TYPTYPHERIX'),
  ('IMC', 'Immunisation Compound', '25', 'HIB'),
  ('IMC', 'Immunisation Compound', '26', 'RUBELLA'),
  ('IMC', 'Immunisation Compound', '27', 'HEPATITIS_B'),
  ('IMC', 'Immunisation Compound', '28', 'HEPATITIS_A'),
  ('IMC', 'Immunisation Compound', '29', 'HEPA2'),
  ('IMC', 'Immunisation Compound', '30', 'MEASLES'),
  ('IMC', 'Immunisation Compound', '31', 'DIPHTHERIA'),
  ('IMC', 'Immunisation Compound', '32', 'TYPTYPHIM'),
  ('IMC', 'Immunisation Compound', '33', 'HEPB_JUN'),
  ('IMC', 'Immunisation Compound', '34', 'HEPA_JUN'),
  ('IME', 'Method Of Administration', '0', 'Data Not Entered'),
  ('IME', 'Method Of Administration', '1', 'Intramuscular'),
  ('IME', 'Method Of Administration', '2', 'Oral'),
  ('IME', 'Method Of Administration', '3', 'Subcutaneous'),
  ('IME', 'Method Of Administration', '4', 'Intradermal'),
  ('IME', 'Method Of Administration', '5', 'Intranasal'),
  ('IMM', 'Immunisation Status', '0', 'Data Not Entered'),
  ('IMM', 'Immunisation Status', '1', 'Given'),
  ('IMM', 'Immunisation Status', '4', 'Refusal to start or complete course'),
  ('IMM', 'Immunisation Status', '9', 'Advised'),
  ('IMT', 'Immunisation Type', '0', ''),
  ('IMT', 'Immunisation Type', '1', 'TETANUS'),
  ('IMT', 'Immunisation Type', '2', 'POLIO'),
  ('IMT', 'Immunisation Type', '3', 'DIPHTHERIA'),
  ('IMT', 'Immunisation Type', '4', 'FLU'),
  ('IMT', 'Immunisation Type', '5', 'PERTUSSIS'),
  ('IMT', 'Immunisation Type', '6', 'HIB'),
  ('IMT', 'Immunisation Type', '7', 'MEASLES'),
  ('IMT', 'Immunisation Type', '8', 'RUBELLA'),
  ('IMT', 'Immunisation Type', '9', 'MUMPS'),
  ('IMT', 'Immunisation Type', '10', 'MENC'),
  ('IMT', 'Immunisation Type', '11', 'HEPA'),
  ('IMT', 'Immunisation Type', '12', 'TYPHOID'),
  ('IMT', 'Immunisation Type', '13', 'PNEUMOCOC'),
  ('IMT', 'Immunisation Type', '14', 'HEPB'),
  ('IMT', 'Immunisation Type', '15', 'BCG'),
  ('IMT', 'Immunisation Type', '16', 'TYPTYPHIM'),
  ('IMT', 'Immunisation Type', '17', 'HEPAMONO'),
  ('IMT', 'Immunisation Type', '18', 'PNEUMOCONJ'),
  ('IMT', 'Immunisation Type', '19', 'HEPAAVAXIM'),
  ('IMT', 'Immunisation Type', '20', 'TYPTYPHERIX'),
  ('IMT', 'Immunisation Type', '21', 'HNIG'),
  ('IMT', 'Immunisation Type', '22', 'MENING'),
  ('IMT', 'Immunisation Type', '23', 'YELLOW'),
  ('IMT', 'Immunisation Type', '24', 'CHOLERA'),
  ('IMT', 'Immunisation Type', '25', 'RABIES'),
  ('IMT', 'Immunisation Type', '26', 'HEPAJUNIOR'),
  ('IMT', 'Immunisation Type', '27', 'HEPAMONOJUNIO'),
  ('IMT', 'Immunisation Type', '28', 'PNEUMOPOLY'),
  ('IMT', 'Immunisation Type', '29', 'HEPATITIS_A'),
  ('IMT', 'Immunisation Type', '30', 'SMALLPOX'),
  ('IMT', 'Immunisation Type', '31', 'HEPATITIS_B'),
  ('IMT', 'Immunisation Type', '32', 'OTHERCOMBINED'),
  ('IMT', 'Immunisation Type', '33', 'HEPAVAQTA'),
  ('IMT', 'Immunisation Type', '34', 'JAPAN'),
  ('IMT', 'Immunisation Type', '35', 'HEPABTWIN'),
  ('IMT', 'Immunisation Type', '36', 'MENACWY'),
  ('IMT', 'Immunisation Type', '37', 'OTHERSINGLE'),
  ('IMT', 'Immunisation Type', '38', 'HEPAEPAX'),
  ('IMT', 'Immunisation Type', '39', 'HBIG'),
  ('IMT', 'Immunisation Type', '40', 'HEPAPMMSD'),
  ('IMT', 'Immunisation Type', '41', 'TICK'),
  ('IMT', 'Immunisation Type', '42', 'TD'),
  ('IMT', 'Immunisation Type', '43', 'VARICELLA'),
  ('IMT', 'Immunisation Type', '44', 'TAB'),
  ('IMT', 'Immunisation Type', '45', 'IGTETANUS'),
  ('IMT', 'Immunisation Type', '46', 'HIBDTP'),
  ('IMT', 'Immunisation Type', '47', 'DTP'),
  ('IMT', 'Immunisation Type', '48', 'ANTHRAX'),
  ('IMT', 'Immunisation Type', '49', 'TYPHUS'),
  ('IMT', 'Immunisation Type', '50', 'MR'),
  ('IMT', 'Immunisation Type', '51', 'MMR'),
  ('IMT', 'Immunisation Type', '52', 'HIBMENC'),
  ('IMT', 'Immunisation Type', '53', 'IGZOSTER'),
  ('IMT', 'Immunisation Type', '54', 'TYPVIVOTIF'),
  ('IMT', 'Immunisation Type', '55', 'DP'),
  ('IMT', 'Immunisation Type', '56', 'IGRABIES'),
  ('IMT', 'Immunisation Type', '57', 'DT'),
  ('IMT', 'Immunisation Type', '58', 'HPV'),
  ('IMT', 'Immunisation Type', '59', 'SMALLPOXUNSUC'),
  ('IMT', 'Immunisation Type', '60', 'PLAGUE'),
  ('IMT', 'Immunisation Type', '61', 'TULARAEMIA'),
  ('IMT', 'Immunisation Type', '62', 'IGANTID'),
  ('IMT', 'Immunisation Type', '63', 'IGCMV'),
  ('IMT', 'Immunisation Type', '64', 'DIPHTHERIAUM'),
  ('IMT', 'Immunisation Type', '66', 'MENU'),
  ('IMT', 'Immunisation Type', '67', 'HPVCER'),
  ('IMT', 'Immunisation Type', '68', 'HEPABAMBRIX'),
  ('IMT', 'Immunisation Type', '69', 'HEPABAMBPA'),
  ('IMT', 'Immunisation Type', '70', 'HEPA2'),
  ('IMT', 'Immunisation Type', '71', 'PFLUGEN'),
  ('IMT', 'Immunisation Type', '72', 'PFLUGSK'),
  ('IMT', 'Immunisation Type', '73', 'PFLUGSKO'),
  ('IMT', 'Immunisation Type', '74', 'PFLUGS'),
  ('IMT', 'Immunisation Type', '75', 'PFLUBAXO'),
  ('IMT', 'Immunisation Type', '76', 'PFLUBAX'),
  ('IMT', 'Immunisation Type', '77', 'HEPA_JUN'),
  ('IMT', 'Immunisation Type', '78', 'PFLUGENO'),
  ('IMT', 'Immunisation Type', '79', 'DTAPIPV'),
  ('IMT', 'Immunisation Type', '80', 'DTAPIPVHIB'),
  ('IMT', 'Immunisation Type', '81', 'DTIPV'),
  ('IMT', 'Immunisation Type', '82', 'PNEUMOCONJ13'),
  ('IMT', 'Immunisation Type', '83', 'DIPTHERIA'),
  ('IMT', 'Immunisation Type', '84', 'FLUSOHP'),
  ('IMT', 'Immunisation Type', '85', 'FLUSPHARMA'),
  ('IMT', 'Immunisation Type', '86', 'ROTAVIRUS'),
  ('IMT', 'Immunisation Type', '87', 'HEPB_JUN'),
  ('IMT', 'Immunisation Type', '88', 'SHINGLES'),
  ('IMT', 'Immunisation Type', '89', 'FLUSIN'),
  ('IMT', 'Immunisation Type', '90', 'HEPAVAQTADULT'),
  ('IMT', 'Immunisation Type', '91', 'SHINGLESOHP'),
  ('IMT', 'Immunisation Type', '92', 'ROTAVIRUS VAC'),
  ('IMT', 'Immunisation Type', '93', 'HPV2'),
  ('IMT', 'Immunisation Type', '94', 'HPVCER2'),
  ('IMT', 'Immunisation Type', '95', 'MENB'),
  ('IMT', 'Immunisation Type', '96', 'PERTUSIS_P'),
  ('IMT', 'Immunisation Type', '97', 'FLUSINOHP'),
  ('IMT', 'Immunisation Type', '98', 'MENBOHP'),
  ('IMT', 'Immunisation Type', '99', 'PERTUSISP_OHP'),
  ('IMT', 'Immunisation Type', '100', 'FLUSIMOHP'),
  ('INP', 'In Practice Options', '0', 'Data Not Entered'),
  ('INP', 'In Practice Options', '1', 'In this Practice'),
  ('INP', 'In Practice Options', '2', 'Out of Practice'),
  ('INP', 'In Practice Options', '3', 'In another Practice'),
  ('INP', 'In Practice Options', '4', 'Source unknown'),
  ('ISI', 'Imms Site Of Administration', '0', 'Data Not Entered'),
  ('ISI', 'Imms Site Of Administration', '1', 'Left arm'),
  ('ISI', 'Imms Site Of Administration', '2', 'Right arm'),
  ('ISI', 'Imms Site Of Administration', '3', 'Left thigh'),
  ('ISI', 'Imms Site Of Administration', '4', 'Right thigh'),
  ('ISI', 'Imms Site Of Administration', '5', 'Left buttock'),
  ('ISI', 'Imms Site Of Administration', '6', 'Right buttock'),
  ('ISI', 'Imms Site Of Administration', '7', 'Other'),
  ('ISI', 'Imms Site Of Administration', '8', 'Upper left thigh'),
  ('ISI', 'Imms Site Of Administration', '9', 'Lower left thigh'),
  ('ISI', 'Imms Site Of Administration', '10', 'Upper right thigh'),
  ('ISI', 'Imms Site Of Administration', '11', 'Lower right thigh'),
  ('IST', 'Immunisation Stage', '0', ''),
  ('IST', 'Immunisation Stage', '1', 'B'),
  ('IST', 'Immunisation Stage', '2', '1'),
  ('IST', 'Immunisation Stage', '3', '2'),
  ('IST', 'Immunisation Stage', '4', '3'),
  ('IST', 'Immunisation Stage', '5', '0'),
  ('IST', 'Immunisation Stage', '6', 'B2'),
  ('IST', 'Immunisation Stage', '7', '4'),
  ('IST', 'Immunisation Stage', '8', ''),
  ('IST', 'Immunisation Stage', '9', '5'),
  ('IST', 'Immunisation Stage', '10', '6'),
  ('KIN', 'Next Of Kin', '0', 'Data Not Entered'),
  ('KIN', 'Next Of Kin', '1', 'Spouse'),
  ('KIN', 'Next Of Kin', '2', 'Sibling'),
  ('KIN', 'Next Of Kin', '3', 'Child'),
  ('KIN', 'Next Of Kin', '4', 'Other relative'),
  ('KIN', 'Next Of Kin', '5', 'Other'),
  ('LAC', 'Feeding', '0', 'Data Not Entered'),
  ('LAC', 'Feeding', '1', 'Breast'),
  ('LAC', 'Feeding', '2', 'Bottle'),
  ('LAC', 'Feeding', '3', 'Breast and bottle'),
  ('LAT', 'Laterality', '0', 'Data Not Entered'),
  ('LAT', 'Laterality', '1', 'Left'),
  ('LAT', 'Laterality', '2', 'Right'),
  ('LAT', 'Laterality', '3', 'Midline'),
  ('LAT', 'Laterality', '4', 'Indeterminate'),
  ('LAT', 'Laterality', '5', 'Bilateral'),
  ('LEG', 'Anatomical Site In Leg', '0', 'Data Not Entered'),
  ('LEG', 'Anatomical Site In Leg', '1', 'Toe'),
  ('LEG', 'Anatomical Site In Leg', '2', 'Foot'),
  ('LEG', 'Anatomical Site In Leg', '3', 'Ankle'),
  ('LEG', 'Anatomical Site In Leg', '4', 'Lower Leg'),
  ('LEG', 'Anatomical Site In Leg', '5', 'Whole Leg'),
  ('LIV', 'Birth Type', '0', 'Data Not Entered'),
  ('LIV', 'Birth Type', '1', 'Live birth'),
  ('LIV', 'Birth Type', '2', 'Still birth'),
  ('LIV', 'Birth Type', '3', 'Miscarriage'),
  ('LIV', 'Birth Type', '4', 'Unknown'),
  ('LMP', 'Lmp Certainty', '0', 'Data Not Entered'),
  ('LMP', 'Lmp Certainty', '1', 'Sure'),
  ('LMP', 'Lmp Certainty', '2', 'Unsure  (use best guess LMP date)'),
  ('LMP', 'Lmp Certainty', '3', 'Very unsure (use best guess LMP date)'),
  ('LOC', 'Over 75 Check Location', '0', 'Data Not Entered'),
  ('LOC', 'Over 75 Check Location', '1', 'Surgery'),
  ('LOC', 'Over 75 Check Location', '2', 'Home'),
  ('MAR', 'Marital Status', '0', 'Data Not Entered'),
  ('MAR', 'Marital Status', '1', 'Single'),
  ('MAR', 'Marital Status', '2', 'Married'),
  ('MAR', 'Marital Status', '3', 'Widowed'),
  ('MAR', 'Marital Status', '4', 'Divorced'),
  ('MAR', 'Marital Status', '5', 'Separated'),
  ('MAR', 'Marital Status', '6', 'Unknown'),
  ('MAR', 'Marital Status', '7', 'Engaged'),
  ('MAR', 'Marital Status', '8', 'Co-habiting'),
  ('MAR', 'Marital Status', '9', 'Remarried'),
  ('MAR', 'Marital Status', '10', 'Stable relationship'),
  ('MAR', 'Marital Status', '11', 'Civil Partnership'),
  ('MBO', 'Maternity Booking Type', '0', 'Data Not Entered'),
  ('MBO', 'Maternity Booking Type', '1', 'Hospital'),
  ('MBO', 'Maternity Booking Type', '2', 'Home delivery'),
  ('MBO', 'Maternity Booking Type', '3', 'GP Unit'),
  ('MOB', 'Mobility Levels', '0', 'Data Not Entered'),
  ('MOB', 'Mobility Levels', '1', 'Level 1'),
  ('MOB', 'Mobility Levels', '2', 'Level 2'),
  ('MOB', 'Mobility Levels', '3', 'Level 3'),
  ('MOB', 'Mobility Levels', '4', 'Level 4'),
  ('MOB', 'Mobility Levels', '5', 'Level 5'),
  ('MOB', 'Mobility Levels', '6', 'Level 6'),
  ('MOB', 'Mobility Levels', '7', 'Level 7'),
  ('MOB', 'Mobility Levels', '8', 'Level 8'),
  ('MOB', 'Mobility Levels', '9', 'Level 9'),
  ('MOB', 'Mobility Levels', '10', 'Level 10'),
  ('MOB', 'Mobility Levels', '11', 'Level 11'),
  ('MOB', 'Mobility Levels', '12', 'Level 12'),
  ('MOB', 'Mobility Levels', '13', 'Level 13'),
  ('MOB', 'Mobility Levels', '14', 'Level 14'),
  ('N_A', 'Normal/abnormal', '0', 'Data Not Entered'),
  ('N_A', 'Normal/abnormal', '1', 'Normal'),
  ('N_A', 'Normal/abnormal', '2', 'Abnormal'),
  ('N_A', 'Normal/abnormal', '3', 'Potential Abnormal'),
  ('N_A', 'Normal/abnormal', '4', ''),
  ('NCO', 'Night Cough', '0', 'Data Not Entered'),
  ('NCO', 'Night Cough', '1', 'No night cough'),
  ('NCO', 'Night Cough', '2', '< 1/week'),
  ('NCO', 'Night Cough', '3', '1 - 3/week'),
  ('NCO', 'Night Cough', '4', '> 3/week'),
  ('OPR', 'Operator', '0', 'Data Not Entered'),
  ('OPR', 'Operator', '1', '<'),
  ('OPR', 'Operator', '2', '<='),
  ('OPR', 'Operator', '3', '='),
  ('OPR', 'Operator', '4', '>'),
  ('OPR', 'Operator', '5', '>='),
  ('OPR', 'Operator', '6', '~'),
  ('P_A', 'Absent/present', '0', 'Data Not Entered'),
  ('P_A', 'Absent/present', '1', 'Absent'),
  ('P_A', 'Absent/present', '2', 'Present'),
  ('P_N', 'Negative/Positive', '0', 'Data Not Entered'),
  ('P_N', 'Negative/Positive', '1', 'Negative'),
  ('P_N', 'Negative/Positive', '2', 'Positive'),
  ('PBP', 'Pretreatment Bp Reading Number', '0', 'Data Not Entered'),
  ('PBP', 'Pretreatment Bp Reading Number', '1', 'First reading'),
  ('PBP', 'Pretreatment Bp Reading Number', '2', 'Second reading'),
  ('PBP', 'Pretreatment Bp Reading Number', '3', 'Third reading'),
  ('PBP', 'Pretreatment Bp Reading Number', '4', '> Third reading'),
  ('PEX', 'Prescription Exemption', '0', 'Data Not Entered'),
  ('PEX', 'Prescription Exemption', '1', 'Under 16 years of age'),
  ('PEX', 'Prescription Exemption', '2', '16, 17 or 18 and in full-time education'),
  ('PEX', 'Prescription Exemption', '3', 'Woman aged 60 or over'),
  ('PEX', 'Prescription Exemption', '4', 'Man aged 60 or over'),
  ('PEX', 'Prescription Exemption', '5', 'Has a maternity/medical exemption certificate'),
  ('PEX', 'Prescription Exemption', '6', 'Has a prescription prepayment certificate'),
  ('PEX', 'Prescription Exemption', '7', 'Receives Income Support/Family credit et'),
  ('PEX', 'Prescription Exemption', '8', 'Has a War Pension exemption certificate'),
  ('PEX', 'Prescription Exemption', '9', 'Not Exempt'),
  ('PEX', 'Prescription Exemption', '10', 'Gets Disability Working Allowance'),
  ('PEX', 'Prescription Exemption', '11', 'Receives Income-based Jobseeker''s Allowance'),
  ('PEX', 'Prescription Exemption', '12', 'Is named on a current HC2 charges certificate'),
  ('PEX', 'Prescription Exemption', '13', 'Was prescribed a free-of-charge contraceptive'),
  ('PEX', 'Prescription Exemption', '14', 'Has a maternity exemption certificate'),
  ('PEX', 'Prescription Exemption', '15', 'Has a medical exemption certificate'),
  ('PEX', 'Prescription Exemption', '16', 'Receives Income Support'),
  ('PEX', 'Prescription Exemption', '17', 'Has WFTC exemption or gets full or reduced WFTC'),
  ('PEX', 'Prescription Exemption', '18', 'Has DPTC exemption or gets full or reduced DPTC'),
  ('PEX', 'Prescription Exemption', '19', 'Aged 60 or over'),
  ('PEX', 'Prescription Exemption', '20', 'Entitled to/has a valid NHS Tax Credit Exemption Certificate'),
  ('PEX', 'Prescription Exemption', '21', 'Has a Partner who gets Pension Credit guarantee credit PCGC'),
  ('PFD', 'Peak Flow Device Type', '0', 'Data Not Entered'),
  ('PFD', 'Peak Flow Device Type', '1', 'Wright'),
  ('PFD', 'Peak Flow Device Type', '2', 'EN13826'),
  ('PHR', 'Problem State', '0', 'Data Not Entered'),
  ('PHR', 'Problem State', '1', 'Satisfactory'),
  ('PHR', 'Problem State', '2', 'Problem'),
  ('PHR', 'Problem State', '3', 'Continue observation'),
  ('PHR', 'Problem State', '4', 'Treatment being received'),
  ('PHR', 'Problem State', '5', 'Referral'),
  ('PHR', 'Problem State', '6', 'Not examined'),
  ('PMR', 'Post Mortem', '0', 'Data Not Entered'),
  ('PMR', 'Post Mortem', '1', 'Post-mortem information included'),
  ('PMR', 'Post Mortem', '2', 'Post-mortem information may be available later'),
  ('PMR', 'Post Mortem', '3', 'Post-mortem not being held'),
  ('PMR', 'Post Mortem', '4', 'Death reported to the Coroner for further action'),
  ('POC', 'Pregnancy Outcome', '0', 'Data Not Entered'),
  ('POC', 'Pregnancy Outcome', '1', 'Live'),
  ('POC', 'Pregnancy Outcome', '2', 'Stillborn'),
  ('POC', 'Pregnancy Outcome', '3', 'Neonatal death'),
  ('POC', 'Pregnancy Outcome', '4', 'Intra-partum death'),
  ('POP', 'Population Base', '0', 'Data Not Entered'),
  ('POP', 'Population Base', '1', 'Age based'),
  ('POP', 'Population Base', '2', 'Age and race based'),
  ('POP', 'Population Base', '3', 'Age and sex based'),
  ('POP', 'Population Base', '4', 'Gestational age based'),
  ('POP', 'Population Base', '5', 'Generic normal range'),
  ('POP', 'Population Base', '6', 'Other (e.g. specific disease based)'),
  ('POP', 'Population Base', '7', 'Race based'),
  ('POP', 'Population Base', '8', 'Race and sex based'),
  ('POP', 'Population Base', '9', 'Sex based'),
  ('POS', 'Posture', '0', 'Data Not Entered'),
  ('POS', 'Posture', '1', 'Sitting'),
  ('POS', 'Posture', '2', 'Lying down'),
  ('POS', 'Posture', '3', 'Standing'),
  ('PRE', 'Presence', '0', 'Data Not Entered'),
  ('PRE', 'Presence', '1', 'Normal'),
  ('PRE', 'Presence', '2', 'Absent'),
  ('PRE', 'Presence', '3', 'Diminished'),
  ('PRE', 'Presence', '4', 'Increased'),
  ('PRE', 'Presence', '5', 'Not examined'),
  ('PRG', 'Practice Region', '1', 'North East'),
  ('PRG', 'Practice Region', '2', 'North West'),
  ('PRG', 'Practice Region', '3', 'Yorkshire & The Humber'),
  ('PRG', 'Practice Region', '4', 'East Midlands'),
  ('PRG', 'Practice Region', '5', 'West Midlands'),
  ('PRG', 'Practice Region', '6', 'East of England'),
  ('PRG', 'Practice Region', '7', 'South West'),
  ('PRG', 'Practice Region', '8', 'South Central'),
  ('PRG', 'Practice Region', '9', 'London'),
  ('PRG', 'Practice Region', '10', 'South East Coast'),
  ('PRG', 'Practice Region', '11', 'Northern Ireland'),
  ('PRG', 'Practice Region', '12', 'Scotland'),
  ('PRG', 'Practice Region', '13', 'Wales'),
  ('PSM', 'Passive Smoking', '0', 'Data Not Entered'),
  ('PSM', 'Passive Smoking', '1', 'Parental'),
  ('PSM', 'Passive Smoking', '2', 'Household'),
  ('PSM', 'Passive Smoking', '3', 'Work place'),
  ('PSM', 'Passive Smoking', '4', 'Other'),
  ('RCT', 'Reaction Type', '0', 'Data Not Entered'),
  ('RCT', 'Reaction Type', '1', 'Allergy'),
  ('RCT', 'Reaction Type', '2', 'Intolerance'),
  ('RCT', 'Reaction Type', '3', 'Adverse Effect'),
  ('REF', 'Elderly Patient Referrals', '0', 'Data Not Entered'),
  ('REF', 'Elderly Patient Referrals', '1', 'Hospital'),
  ('REF', 'Elderly Patient Referrals', '2', 'Community care'),
  ('REF', 'Elderly Patient Referrals', '3', 'Social services'),
  ('REF', 'Elderly Patient Referrals', '4', 'GP'),
  ('REF', 'Elderly Patient Referrals', '5', 'Other Agency'),
  ('RES', 'Residence Types', '0', 'Data Not Entered'),
  ('RES', 'Residence Types', '1', 'Nursing home'),
  ('RES', 'Residence Types', '2', 'Rest home'),
  ('RES', 'Residence Types', '3', 'Warden supported'),
  ('RES', 'Residence Types', '4', 'Sheltered accomodation'),
  ('RES', 'Residence Types', '5', 'Own home'),
  ('RES', 'Residence Types', '6', 'Other'),
  ('RFT', 'Referral Type', '0', 'Data Not Entered'),
  ('RFT', 'Referral Type', '1', 'In Patient'),
  ('RFT', 'Referral Type', '2', 'Day Case'),
  ('RFT', 'Referral Type', '3', 'Out Patient'),
  ('RFT', 'Referral Type', '4', 'Domiciliary'),
  ('RFT', 'Referral Type', '5', 'Direct Access'),
  ('RFT', 'Referral Type', '6', 'PHCT'),
  ('RFT', 'Referral Type', '7', 'Other'),
  ('RIN', 'Reason Indicator', '0', 'Data Not Entered'),
  ('RIN', 'Reason Indicator', '1', 'Epidemic'),
  ('RIN', 'Reason Indicator', '2', 'Special Risk Group'),
  ('RIN', 'Reason Indicator', '3', 'Routine Measure'),
  ('RIN', 'Reason Indicator', '4', 'Traveller'),
  ('ROL', 'Role Of Staff', '0', 'Data Not Entered'),
  ('ROL', 'Role Of Staff', '1', 'Senior Partner'),
  ('ROL', 'Role Of Staff', '2', 'Partner'),
  ('ROL', 'Role Of Staff', '3', 'Assistant'),
  ('ROL', 'Role Of Staff', '4', 'Associate'),
  ('ROL', 'Role Of Staff', '5', 'Non-commercial local rota of less than 10 GPs'),
  ('ROL', 'Role Of Staff', '6', 'Commercial Deputising service'),
  ('ROL', 'Role Of Staff', '7', 'Locum'),
  ('ROL', 'Role Of Staff', '8', 'GP Registrar'),
  ('ROL', 'Role Of Staff', '9', 'Consultant'),
  ('ROL', 'Role Of Staff', '10', 'Sole Practitioner'),
  ('ROL', 'Role Of Staff', '11', 'Practice Nurse'),
  ('ROL', 'Role Of Staff', '12', 'Health Visitor'),
  ('ROL', 'Role Of Staff', '13', 'Community Nurse'),
  ('ROL', 'Role Of Staff', '14', 'Midwife'),
  ('ROL', 'Role Of Staff', '15', 'Community Psychiatric Nurse'),
  ('ROL', 'Role Of Staff', '16', 'Social Worker'),
  ('ROL', 'Role Of Staff', '17', 'Pharmacist'),
  ('ROL', 'Role Of Staff', '18', 'Dispenser'),
  ('ROL', 'Role Of Staff', '19', 'Non-qualified Dispenser'),
  ('ROL', 'Role Of Staff', '20', 'Practice Manager'),
  ('ROL', 'Role Of Staff', '21', 'Fund Manager'),
  ('ROL', 'Role Of Staff', '22', 'Business Manager'),
  ('ROL', 'Role Of Staff', '23', 'Administrator'),
  ('ROL', 'Role Of Staff', '24', 'Secretary'),
  ('ROL', 'Role Of Staff', '25', 'Receptionist'),
  ('ROL', 'Role Of Staff', '26', 'Physiotherapist'),
  ('ROL', 'Role Of Staff', '27', 'Chiropodist'),
  ('ROL', 'Role Of Staff', '28', 'Dentist'),
  ('ROL', 'Role Of Staff', '29', 'Dietician'),
  ('ROL', 'Role Of Staff', '30', 'Counsellor'),
  ('ROL', 'Role Of Staff', '31', 'Osteopath'),
  ('ROL', 'Role Of Staff', '32', 'Maintenance staff'),
  ('ROL', 'Role Of Staff', '33', 'Other Health Care Professional'),
  ('ROL', 'Role Of Staff', '34', 'Hospital Nurse'),
  ('ROL', 'Role Of Staff', '35', 'Community Medical Officer'),
  ('ROL', 'Role Of Staff', '36', 'School Nurse'),
  ('ROL', 'Role Of Staff', '37', 'Health Education Officer'),
  ('ROL', 'Role Of Staff', '38', 'Contact Tracing Nurse'),
  ('ROL', 'Role Of Staff', '39', 'Stomatherapist'),
  ('ROL', 'Role Of Staff', '40', 'Computer Manager'),
  ('ROL', 'Role Of Staff', '41', 'Interpreter/Link Worker'),
  ('ROL', 'Role Of Staff', '42', 'Chiropractor'),
  ('ROL', 'Role Of Staff', '43', 'Acupuncturist'),
  ('ROL', 'Role Of Staff', '44', 'Homeopath'),
  ('ROL', 'Role Of Staff', '45', 'Mental Handicap Nurse'),
  ('ROL', 'Role Of Staff', '46', 'Carer'),
  ('ROL', 'Role Of Staff', '47', 'Salaried Partner'),
  ('ROL', 'Role Of Staff', '48', 'Occupational Therapist'),
  ('ROL', 'Role Of Staff', '49', 'Speech Therapist'),
  ('ROL', 'Role Of Staff', '50', 'GP Retainer'),
  ('ROL', 'Role Of Staff', '51', 'Phlebotomist'),
  ('ROL', 'Role Of Staff', '52', 'Other Medical & Dental'),
  ('ROL', 'Role Of Staff', '53', 'Other Students'),
  ('ROL', 'Role Of Staff', '54', 'Other Nursing & Midwifery'),
  ('ROL', 'Role Of Staff', '55', 'Other Allied Health Professionals'),
  ('ROL', 'Role Of Staff', '56', 'Other Professional Scientific & Technical'),
  ('ROL', 'Role Of Staff', '57', 'Other Healthcare Scientists'),
  ('ROL', 'Role Of Staff', '58', 'Other Additional Clinical Services'),
  ('ROL', 'Role Of Staff', '59', 'Other Admin & Clerical'),
  ('ROL', 'Role Of Staff', '60', 'Clinical Practitioner Access Role'),
  ('ROL', 'Role Of Staff', '61', 'Nurse Access Role'),
  ('ROL', 'Role Of Staff', '62', 'Nurse Manager Access Role'),
  ('ROL', 'Role Of Staff', '63', 'Health Professional Access Role'),
  ('ROL', 'Role Of Staff', '64', 'Healthcare Student Access Role'),
  ('ROL', 'Role Of Staff', '65', 'Biomedical Scientist Access Role'),
  ('ROL', 'Role Of Staff', '66', 'Clinical Coder Access Role'),
  ('ROL', 'Role Of Staff', '67', 'Optometrist'),
  ('ROL', 'Role Of Staff', '68', 'Radiographer'),
  ('SED', 'Medical Entry', '0', 'Missing'),
  ('SED', 'Medical Entry', '1', 'Symptom'),
  ('SED', 'Medical Entry', '2', 'Examination'),
  ('SED', 'Medical Entry', '3', 'Diagnosis'),
  ('SED', 'Medical Entry', '4', 'Intervention'),
  ('SED', 'Medical Entry', '5', 'Management'),
  ('SED', 'Medical Entry', '6', 'Administration'),
  ('SED', 'Medical Entry', '7', 'Presenting complaint'),
  ('SED', 'Medical Entry', '8', ' '),
  ('SEV', 'Severity', '0', 'Data Not Entered'),
  ('SEV', 'Severity', '1', 'Minimal'),
  ('SEV', 'Severity', '2', 'Mild'),
  ('SEV', 'Severity', '3', 'Moderate'),
  ('SEV', 'Severity', '4', 'Severe'),
  ('SEV', 'Severity', '5', 'Very severe'),
  ('SEV', 'Severity', '6', 'Potentially Fatal'),
  ('SEX', 'Sex', '0', 'Data Not Entered'),
  ('SEX', 'Sex', '1', 'Male'),
  ('SEX', 'Sex', '2', 'Female'),
  ('SEX', 'Sex', '3', 'Indeterminate'),
  ('SEX', 'Sex', '4', 'Unknown'),
  ('SIN', 'Delivery Outcome', '0', 'Data Not Entered'),
  ('SIN', 'Delivery Outcome', '1', 'Singleton'),
  ('SIN', 'Delivery Outcome', '2', 'Twin'),
  ('SIN', 'Delivery Outcome', '3', 'Triplet'),
  ('SIN', 'Delivery Outcome', '4', 'Multiple'),
  ('SIN', 'Delivery Outcome', '5', 'Unknown'),
  ('SOU', 'Source Of Referral', '0', 'No Data Entered/Missing'),
  ('SOU', 'Source Of Referral', '1', 'GP Referral'),
  ('SOU', 'Source Of Referral', '2', 'Self'),
  ('SOU', 'Source Of Referral', '3', '3rd Party'),
  ('SOU', 'Source Of Referral', '4', 'PHCT'),
  ('SPE', 'Fhsa Specialty', '0', 'No Data Entered'),
  ('SPE', 'Fhsa Specialty', '1', 'General Surgical'),
  ('SPE', 'Fhsa Specialty', '2', 'General Medical'),
  ('SPE', 'Fhsa Specialty', '3', 'Orthopaedic'),
  ('SPE', 'Fhsa Specialty', '4', 'Rheumatology'),
  ('SPE', 'Fhsa Specialty', '5', 'Ear, Nose and Throat'),
  ('SPE', 'Fhsa Specialty', '6', 'Gynaecology'),
  ('SPE', 'Fhsa Specialty', '7', 'Obstetrics'),
  ('SPE', 'Fhsa Specialty', '8', 'Paediatrics'),
  ('SPE', 'Fhsa Specialty', '9', 'Ophthalmology'),
  ('SPE', 'Fhsa Specialty', '10', 'Psychiatry'),
  ('SPE', 'Fhsa Specialty', '11', 'Geriatrics'),
  ('SPE', 'Fhsa Specialty', '12', 'Dermatology'),
  ('SPE', 'Fhsa Specialty', '13', 'Neurology'),
  ('SPE', 'Fhsa Specialty', '14', 'Genito-Urinary'),
  ('SPE', 'Fhsa Specialty', '15', 'X-Ray'),
  ('SPE', 'Fhsa Specialty', '16', 'Pathology'),
  ('SPE', 'Fhsa Specialty', '17', 'Other'),
  ('SPE', 'Fhsa Specialty', '18', 'Non-referral report'),
  ('SPE', 'Fhsa Specialty', '19', ''),
  ('SUM', 'Specimen Unit Of Measure', '0', 'No Data Entered'),
  ('SUM', 'Specimen Unit Of Measure', '1', '%'),
  ('SUM', 'Specimen Unit Of Measure', '2', '(bdsk u)'),
  ('SUM', 'Specimen Unit Of Measure', '3', '(bsa)'),
  ('SUM', 'Specimen Unit Of Measure', '4', '(cfU)'),
  ('SUM', 'Specimen Unit Of Measure', '5', '(knk u)'),
  ('SUM', 'Specimen Unit Of Measure', '6', '(mclg u)'),
  ('SUM', 'Specimen Unit Of Measure', '7', 'OD'),
  ('SUM', 'Specimen Unit Of Measure', '8', '(pa)'),
  ('SUM', 'Specimen Unit Of Measure', '9', 'pH'),
  ('SUM', 'Specimen Unit Of Measure', '10', '(ppb)'),
  ('SUM', 'Specimen Unit Of Measure', '11', '(ppm)'),
  ('SUM', 'Specimen Unit Of Measure', '12', '(pu)'),
  ('SUM', 'Specimen Unit Of Measure', '13', '(td u)'),
  ('SUM', 'Specimen Unit Of Measure', '14', '/(hpf)'),
  ('SUM', 'Specimen Unit Of Measure', '15', '/day'),
  ('SUM', 'Specimen Unit Of Measure', '16', '/hour'),
  ('SUM', 'Specimen Unit Of Measure', '17', '/L'),
  ('SUM', 'Specimen Unit Of Measure', '18', '/m3'),
  ('SUM', 'Specimen Unit Of Measure', '19', '/min'),
  ('SUM', 'Specimen Unit Of Measure', '20', '/minute'),
  ('SUM', 'Specimen Unit Of Measure', '21', '/mL'),
  ('SUM', 'Specimen Unit Of Measure', '22', '/month'),
  ('SUM', 'Specimen Unit Of Measure', '23', '/second'),
  ('SUM', 'Specimen Unit Of Measure', '24', '/week'),
  ('SUM', 'Specimen Unit Of Measure', '25', '/year'),
  ('SUM', 'Specimen Unit Of Measure', '26', '1'),
  ('SUM', 'Specimen Unit Of Measure', '27', '1(tot)'),
  ('SUM', 'Specimen Unit Of Measure', '28', '1/mL'),
  ('SUM', 'Specimen Unit Of Measure', '29', '10*-2(%)'),
  ('SUM', 'Specimen Unit Of Measure', '30', '10*-3(%)'),
  ('SUM', 'Specimen Unit Of Measure', '31', '10*12/L'),
  ('SUM', 'Specimen Unit Of Measure', '32', '10*3(rbc)'),
  ('SUM', 'Specimen Unit Of Measure', '33', '10*3/L'),
  ('SUM', 'Specimen Unit Of Measure', '34', '10*3/mL'),
  ('SUM', 'Specimen Unit Of Measure', '35', '10*6/L'),
  ('SUM', 'Specimen Unit Of Measure', '36', '10*6/mL'),
  ('SUM', 'Specimen Unit Of Measure', '37', '10*9/L'),
  ('SUM', 'Specimen Unit Of Measure', '38', '10*9/mL'),
  ('SUM', 'Specimen Unit Of Measure', '39', 'degC'),
  ('SUM', 'Specimen Unit Of Measure', '40', 'cm(H2O)'),
  ('SUM', 'Specimen Unit Of Measure', '41', 'd'),
  ('SUM', 'Specimen Unit Of Measure', '42', 'dB'),
  ('SUM', 'Specimen Unit Of Measure', '43', 'dBA'),
  ('SUM', 'Specimen Unit Of Measure', '44', 'deg'),
  ('SUM', 'Specimen Unit Of Measure', '45', 'ft'),
  ('SUM', 'Specimen Unit Of Measure', '46', 'fg'),
  ('SUM', 'Specimen Unit Of Measure', '47', 'fL'),
  ('SUM', 'Specimen Unit Of Measure', '48', 'fmol'),
  ('SUM', 'Specimen Unit Of Measure', '49', 'g'),
  ('SUM', 'Specimen Unit Of Measure', '50', 'g(creat)'),
  ('SUM', 'Specimen Unit Of Measure', '51', 'g(hgb)'),
  ('SUM', 'Specimen Unit Of Measure', '52', 'g(tot_nit)'),
  ('SUM', 'Specimen Unit Of Measure', '53', 'g(tot_prot)'),
  ('SUM', 'Specimen Unit Of Measure', '54', 'g(wet_tis)'),
  ('SUM', 'Specimen Unit Of Measure', '55', 'g/d'),
  ('SUM', 'Specimen Unit Of Measure', '56', 'g/dL'),
  ('SUM', 'Specimen Unit Of Measure', '57', 'g/L'),
  ('SUM', 'Specimen Unit Of Measure', '58', 'h'),
  ('SUM', 'Specimen Unit Of Measure', '59', 'IU'),
  ('SUM', 'Specimen Unit Of Measure', '60', 'IU/d'),
  ('SUM', 'Specimen Unit Of Measure', '61', 'IU/L'),
  ('SUM', 'Specimen Unit Of Measure', '62', 'IU/mL'),
  ('SUM', 'Specimen Unit Of Measure', '63', 'kat'),
  ('SUM', 'Specimen Unit Of Measure', '64', 'kat/kg'),
  ('SUM', 'Specimen Unit Of Measure', '65', 'kat/L'),
  ('SUM', 'Specimen Unit Of Measure', '66', 'Kgs'),
  ('SUM', 'Specimen Unit Of Measure', '67', '/kg(body wt)'),
  ('SUM', 'Specimen Unit Of Measure', '68', 'kg/L'),
  ('SUM', 'Specimen Unit Of Measure', '69', 'kpal'),
  ('SUM', 'Specimen Unit Of Measure', '70', 'kU/L'),
  ('SUM', 'Specimen Unit Of Measure', '71', 'L/min'),
  ('SUM', 'Specimen Unit Of Measure', '72', 'lm'),
  ('SUM', 'Specimen Unit Of Measure', '73', 'lm/m2'),
  ('SUM', 'Specimen Unit Of Measure', '74', 'm'),
  ('SUM', 'Specimen Unit Of Measure', '75', 'm/s'),
  ('SUM', 'Specimen Unit Of Measure', '76', 'm/s2'),
  ('SUM', 'Specimen Unit Of Measure', '77', 'm2'),
  ('SUM', 'Specimen Unit Of Measure', '78', 'meq'),
  ('SUM', 'Specimen Unit Of Measure', '79', 'meq/L'),
  ('SUM', 'Specimen Unit Of Measure', '80', 'mg'),
  ('SUM', 'Specimen Unit Of Measure', '81', 'mg/d'),
  ('SUM', 'Specimen Unit Of Measure', '82', 'mg/dL'),
  ('SUM', 'Specimen Unit Of Measure', '83', 'mg/L'),
  ('SUM', 'Specimen Unit Of Measure', '84', 'mg/m3'),
  ('SUM', 'Specimen Unit Of Measure', '85', 'mg/min'),
  ('SUM', 'Specimen Unit Of Measure', '86', 'mg/mmol'),
  ('SUM', 'Specimen Unit Of Measure', '87', 'min'),
  ('SUM', 'Specimen Unit Of Measure', '88', 'mU/mL'),
  ('SUM', 'Specimen Unit Of Measure', '89', 'mL'),
  ('SUM', 'Specimen Unit Of Measure', '90', 'mL/min'),
  ('SUM', 'Specimen Unit Of Measure', '91', 'mL/s'),
  ('SUM', 'Specimen Unit Of Measure', '92', 'mm'),
  ('SUM', 'Specimen Unit Of Measure', '93', 'mm(Hg)'),
  ('SUM', 'Specimen Unit Of Measure', '94', 'mm/h'),
  ('SUM', 'Specimen Unit Of Measure', '95', 'mmol/d'),
  ('SUM', 'Specimen Unit Of Measure', '96', 'mmol/L'),
  ('SUM', 'Specimen Unit Of Measure', '97', 'mmol/mol'),
  ('SUM', 'Specimen Unit Of Measure', '98', 'mol/kg'),
  ('SUM', 'Specimen Unit Of Measure', '99', 'mol/L'),
  ('SUM', 'Specimen Unit Of Measure', '100', 'mol/s'),
  ('SUM', 'Specimen Unit Of Measure', '101', 'month'),
  ('SUM', 'Specimen Unit Of Measure', '102', 'mosmol/kg'),
  ('SUM', 'Specimen Unit Of Measure', '103', 'mosmol/L'),
  ('SUM', 'Specimen Unit Of Measure', '104', 'ng'),
  ('SUM', 'Specimen Unit Of Measure', '105', 'ng/L'),
  ('SUM', 'Specimen Unit Of Measure', '106', 'ng/mL'),
  ('SUM', 'Specimen Unit Of Measure', '107', 'nkat'),
  ('SUM', 'Specimen Unit Of Measure', '108', 'nm'),
  ('SUM', 'Specimen Unit Of Measure', '109', 'nmol/d'),
  ('SUM', 'Specimen Unit Of Measure', '110', 'nmol/L'),
  ('SUM', 'Specimen Unit Of Measure', '111', 'nmol/s'),
  ('SUM', 'Specimen Unit Of Measure', '112', 'ns'),
  ('SUM', 'Specimen Unit Of Measure', '113', 'Pa'),
  ('SUM', 'Specimen Unit Of Measure', '114', 'pg'),
  ('SUM', 'Specimen Unit Of Measure', '115', 'pg/L'),
  ('SUM', 'Specimen Unit Of Measure', '116', 'pg/mL'),
  ('SUM', 'Specimen Unit Of Measure', '117', 'pkat'),
  ('SUM', 'Specimen Unit Of Measure', '118', 'pm'),
  ('SUM', 'Specimen Unit Of Measure', '119', 'pmol'),
  ('SUM', 'Specimen Unit Of Measure', '120', 'pmol/L'),
  ('SUM', 'Specimen Unit Of Measure', '121', 'ps'),
  ('SUM', 'Specimen Unit Of Measure', '122', 'rad'),
  ('SUM', 'Specimen Unit Of Measure', '123', 'rem'),
  ('SUM', 'Specimen Unit Of Measure', '124', 's'),
  ('SUM', 'Specimen Unit Of Measure', '125', 'stone'),
  ('SUM', 'Specimen Unit Of Measure', '126', 'u'),
  ('SUM', 'Specimen Unit Of Measure', '127', 'U/L'),
  ('SUM', 'Specimen Unit Of Measure', '128', 'ueq'),
  ('SUM', 'Specimen Unit Of Measure', '129', 'ug'),
  ('SUM', 'Specimen Unit Of Measure', '130', 'ug/d'),
  ('SUM', 'Specimen Unit Of Measure', '131', 'ug/dL'),
  ('SUM', 'Specimen Unit Of Measure', '132', 'ug/g'),
  ('SUM', 'Specimen Unit Of Measure', '133', 'ug/L'),
  ('SUM', 'Specimen Unit Of Measure', '134', 'ug/min'),
  ('SUM', 'Specimen Unit Of Measure', '135', 'uiu'),
  ('SUM', 'Specimen Unit Of Measure', '136', 'ukat'),
  ('SUM', 'Specimen Unit Of Measure', '137', 'um'),
  ('SUM', 'Specimen Unit Of Measure', '138', 'umol'),
  ('SUM', 'Specimen Unit Of Measure', '139', 'umol/d'),
  ('SUM', 'Specimen Unit Of Measure', '140', 'umol/g(creat)'),
  ('SUM', 'Specimen Unit Of Measure', '141', 'umol/h/g(Hb)'),
  ('SUM', 'Specimen Unit Of Measure', '142', 'umol/L'),
  ('SUM', 'Specimen Unit Of Measure', '143', 'umol/min'),
  ('SUM', 'Specimen Unit Of Measure', '144', 'umol/mL/h'),
  ('SUM', 'Specimen Unit Of Measure', '145', 'umol/mmol'),
  ('SUM', 'Specimen Unit Of Measure', '146', 'us'),
  ('SUM', 'Specimen Unit Of Measure', '147', 'week'),
  ('SUM', 'Specimen Unit Of Measure', '148', 'year'),
  ('SUM', 'Specimen Unit Of Measure', '149', 'MicroU/L'),
  ('SUM', 'Specimen Unit Of Measure', '150', 'cms'),
  ('SUM', 'Specimen Unit Of Measure', '151', 'ratio'),
  ('SUM', 'Specimen Unit Of Measure', '152', 'second'),
  ('SUM', 'Specimen Unit Of Measure', '153', '10*9'),
  ('SUM', 'Specimen Unit Of Measure', '154', 'L'),
  ('SUM', 'Specimen Unit Of Measure', '155', '10*6'),
  ('SUM', 'Specimen Unit Of Measure', '156', 'mmol'),
  ('SUM', 'Specimen Unit Of Measure', '157', '10*3'),
  ('SUM', 'Specimen Unit Of Measure', '158', 'mPas'),
  ('SUM', 'Specimen Unit Of Measure', '159', 'cP'),
  ('SUM', 'Specimen Unit Of Measure', '160', 'mU/L'),
  ('SUM', 'Specimen Unit Of Measure', '161', '1/1'),
  ('SUM', 'Specimen Unit Of Measure', '162', '/100(WBC)'),
  ('SUM', 'Specimen Unit Of Measure', '164', '/uL'),
  ('SUM', 'Specimen Unit Of Measure', '165', 'IU/dL'),
  ('SUM', 'Specimen Unit Of Measure', '166', 'kg'),
  ('SUM', 'Specimen Unit Of Measure', '167', 'kIU/L'),
  ('SUM', 'Specimen Unit Of Measure', '168', 'kPa'),
  ('SUM', 'Specimen Unit Of Measure', '169', 'mg/mmol(creat)'),
  ('SUM', 'Specimen Unit Of Measure', '170', 'mIU/L'),
  ('SUM', 'Specimen Unit Of Measure', '171', 'mmol/mmol(creat)'),
  ('SUM', 'Specimen Unit Of Measure', '172', 'mPa.s'),
  ('SUM', 'Specimen Unit Of Measure', '173', 'nmol/L/h'),
  ('SUM', 'Specimen Unit Of Measure', '174', 'nmol/L/hr'),
  ('SUM', 'Specimen Unit Of Measure', '175', 'U/dL'),
  ('SUM', 'Specimen Unit Of Measure', '176', 'U/g'),
  ('SUM', 'Specimen Unit Of Measure', '177', 'U/g(Hb)'),
  ('SUM', 'Specimen Unit Of Measure', '178', 'U/mL'),
  ('SUM', 'Specimen Unit Of Measure', '179', 'ug/mL'),
  ('SUM', 'Specimen Unit Of Measure', '180', 'umol/mol'),
  ('SUM', 'Specimen Unit Of Measure', '181', 'umol/mol(Hb)'),
  ('SUM', 'Specimen Unit Of Measure', '182', 'uu/mL'),
  ('SUM', 'Specimen Unit Of Measure', '183', '10*-2'),
  ('SUM', 'Specimen Unit Of Measure', '184', '10*-3'),
  ('SUM', 'Specimen Unit Of Measure', '185', 'L/L'),
  ('SUM', 'Specimen Unit Of Measure', '186', 'kua/L'),
  ('SUM', 'Specimen Unit Of Measure', '187', 'mmol/mmol'),
  ('SUM', 'Specimen Unit Of Measure', '188', 'nmol/g'),
  ('SUM', 'Specimen Unit Of Measure', '189', 'nmol/h/mL(RBC)'),
  ('SUM', 'Specimen Unit Of Measure', '190', 'nmol/mL/min'),
  ('SUM', 'Specimen Unit Of Measure', '191', 'nmol/mmol'),
  ('SUM', 'Specimen Unit Of Measure', '192', 'pmol/h/mg(Hb)'),
  ('SUM', 'Specimen Unit Of Measure', '193', 'uU/spec'),
  ('SUM', 'Specimen Unit Of Measure', '194', 'g/mol'),
  ('SUM', 'Specimen Unit Of Measure', '195', 'titre'),
  ('SUM', 'Specimen Unit Of Measure', '196', 'mg/12hrs'),
  ('SUM', 'Specimen Unit Of Measure', '197', 'SD'),
  ('SUM', 'Specimen Unit Of Measure', '198', '/cu.mm'),
  ('SUM', 'Specimen Unit Of Measure', '199', 'GPL/ml'),
  ('SUM', 'Specimen Unit Of Measure', '200', 'MPL/ml'),
  ('SUM', 'Specimen Unit Of Measure', '201', 'ugFEU/ml'),
  ('SUM', 'Specimen Unit Of Measure', '202', 'mOsm/kg'),
  ('SUM', 'Specimen Unit Of Measure', '203', 'GPL U/ml'),
  ('SUM', 'Specimen Unit Of Measure', '204', 'GPM U/ml'),
  ('SUM', 'Specimen Unit Of Measure', '205', 'mmol/mol Hb'),
  ('SUM', 'Specimen Unit Of Measure', '206', 'nmol/gHb/h'),
  ('SUM', 'Specimen Unit Of Measure', '207', 'ml/min/1.73m'),
  ('SUM', 'Specimen Unit Of Measure', '208', 'ml/min/1.73m*2'),
  ('SUM', 'Specimen Unit Of Measure', '209', '#/[tot]'),
  ('SUM', 'Specimen Unit Of Measure', '210', '#/HPF'),
  ('SUM', 'Specimen Unit Of Measure', '211', '#G ( )/L'),
  ('SUM', 'Specimen Unit Of Measure', '212', '#k ( )/L'),
  ('SUM', 'Specimen Unit Of Measure', '213', '#M ( )/L'),
  ('SUM', 'Specimen Unit Of Measure', '214', '#T ( )/L'),
  ('SUM', 'Specimen Unit Of Measure', '215', '%Hb'),
  ('SUM', 'Specimen Unit Of Measure', '216', '/g(Hb)'),
  ('SUM', 'Specimen Unit Of Measure', '217', '/m*3'),
  ('SUM', 'Specimen Unit Of Measure', '218', 'AU/L'),
  ('SUM', 'Specimen Unit Of Measure', '219', 'cell/L'),
  ('SUM', 'Specimen Unit Of Measure', '220', 'cm'),
  ('SUM', 'Specimen Unit Of Measure', '221', 'copy/L'),
  ('SUM', 'Specimen Unit Of Measure', '222', 'fg/L'),
  ('SUM', 'Specimen Unit Of Measure', '223', 'g/24h'),
  ('SUM', 'Specimen Unit Of Measure', '224', 'g/h'),
  ('SUM', 'Specimen Unit Of Measure', '225', 'g/kg'),
  ('SUM', 'Specimen Unit Of Measure', '226', 'Gcell/L'),
  ('SUM', 'Specimen Unit Of Measure', '227', 'Gcopy/L'),
  ('SUM', 'Specimen Unit Of Measure', '228', 'inch'),
  ('SUM', 'Specimen Unit Of Measure', '229', 'INR U'),
  ('SUM', 'Specimen Unit Of Measure', '230', 'kAU/L'),
  ('SUM', 'Specimen Unit Of Measure', '231', 'kcell/L'),
  ('SUM', 'Specimen Unit Of Measure', '232', 'kcopy/L'),
  ('SUM', 'Specimen Unit Of Measure', '233', 'L/24h'),
  ('SUM', 'Specimen Unit Of Measure', '234', 'L/h'),
  ('SUM', 'Specimen Unit Of Measure', '235', 'lm/m*2'),
  ('SUM', 'Specimen Unit Of Measure', '236', 'm*2'),
  ('SUM', 'Specimen Unit Of Measure', '237', 'm/s*2'),
  ('SUM', 'Specimen Unit Of Measure', '238', 'MAU/L'),
  ('SUM', 'Specimen Unit Of Measure', '239', 'Mcell/L'),
  ('SUM', 'Specimen Unit Of Measure', '240', 'Mcopy/L'),
  ('SUM', 'Specimen Unit Of Measure', '241', 'mg/24h'),
  ('SUM', 'Specimen Unit Of Measure', '242', 'mg/g(dry wt)'),
  ('SUM', 'Specimen Unit Of Measure', '243', 'mg/g(wet wt)'),
  ('SUM', 'Specimen Unit Of Measure', '244', 'mg/h'),
  ('SUM', 'Specimen Unit Of Measure', '245', 'mg/kg'),
  ('SUM', 'Specimen Unit Of Measure', '246', 'mg/m*3'),
  ('SUM', 'Specimen Unit Of Measure', '247', 'mg/mg'),
  ('SUM', 'Specimen Unit Of Measure', '248', 'mIU/mL'),
  ('SUM', 'Specimen Unit Of Measure', '249', 'mL/24h/1.73m*2'),
  ('SUM', 'Specimen Unit Of Measure', '250', 'mL/h'),
  ('SUM', 'Specimen Unit Of Measure', '251', 'mL/min/1.73m*2'),
  ('SUM', 'Specimen Unit Of Measure', '252', 'mmol/24h'),
  ('SUM', 'Specimen Unit Of Measure', '253', 'mmol/g(dry wt)'),
  ('SUM', 'Specimen Unit Of Measure', '254', 'mmol/g(wet wt)'),
  ('SUM', 'Specimen Unit Of Measure', '255', 'mmol/kg'),
  ('SUM', 'Specimen Unit Of Measure', '256', 'MoM'),
  ('SUM', 'Specimen Unit Of Measure', '257', 'ng/mL/h'),
  ('SUM', 'Specimen Unit Of Measure', '258', 'nmol/10*9(platelets)'),
  ('SUM', 'Specimen Unit Of Measure', '259', 'nmol/24h'),
  ('SUM', 'Specimen Unit Of Measure', '260', 'nmol/h/mL'),
  ('SUM', 'Specimen Unit Of Measure', '261', 'nmol/kg'),
  ('SUM', 'Specimen Unit Of Measure', '262', 'nmol/mmol(creat)'),
  ('SUM', 'Specimen Unit Of Measure', '263', 'nmol/mol(creat)'),
  ('SUM', 'Specimen Unit Of Measure', '264', 'PFU'),
  ('SUM', 'Specimen Unit Of Measure', '265', 'pL'),
  ('SUM', 'Specimen Unit Of Measure', '266', 'pmol/24h'),
  ('SUM', 'Specimen Unit Of Measure', '267', 'pmol/kg'),
  ('SUM', 'Specimen Unit Of Measure', '268', 'Tcell/L'),
  ('SUM', 'Specimen Unit Of Measure', '269', 'U'),
  ('SUM', 'Specimen Unit Of Measure', '270', 'U/d'),
  ('SUM', 'Specimen Unit Of Measure', '271', 'ug/24h'),
  ('SUM', 'Specimen Unit Of Measure', '272', 'ug/g(dry wt)'),
  ('SUM', 'Specimen Unit Of Measure', '273', 'ug/g(wet wt)'),
  ('SUM', 'Specimen Unit Of Measure', '274', 'ug/h'),
  ('SUM', 'Specimen Unit Of Measure', '275', 'ug/mmol(creat)'),
  ('SUM', 'Specimen Unit Of Measure', '276', 'uIU/L'),
  ('SUM', 'Specimen Unit Of Measure', '277', 'uL'),
  ('SUM', 'Specimen Unit Of Measure', '278', 'umol/24h'),
  ('SUM', 'Specimen Unit Of Measure', '279', 'umol/g(dry wt)'),
  ('SUM', 'Specimen Unit Of Measure', '280', 'umol/g(wet wt)'),
  ('SUM', 'Specimen Unit Of Measure', '281', 'umol/h/g(Prot)'),
  ('SUM', 'Specimen Unit Of Measure', '282', 'umol/h/L'),
  ('SUM', 'Specimen Unit Of Measure', '283', 'umol/kg'),
  ('SUM', 'Specimen Unit Of Measure', '284', 'umol/mmol(creat)'),
  ('SUM', 'Specimen Unit Of Measure', '285', 'uU/L'),
  ('SUM', 'Specimen Unit Of Measure', '286', 'ngTDP/g Hb'),
  ('SUM', 'Specimen Unit Of Measure', '287', 'pmol/g Hb'),
  ('TOF', 'Time Off In Last 3 Months', '0', 'Data Not Entered'),
  ('TOF', 'Time Off In Last 3 Months', '1', 'No time off'),
  ('TOF', 'Time Off In Last 3 Months', '2', '1 - 2 days'),
  ('TOF', 'Time Off In Last 3 Months', '3', '3 - 10 days'),
  ('TOF', 'Time Off In Last 3 Months', '4', '> 10 days'),
  ('TQU', 'Test Qualifier', '0', 'Data Not Entered'),
  ('TQU', 'Test Qualifier', '1', '<'),
  ('TQU', 'Test Qualifier', '2', '<='),
  ('TQU', 'Test Qualifier', '3', '='),
  ('TQU', 'Test Qualifier', '4', '>'),
  ('TQU', 'Test Qualifier', '5', '>='),
  ('TQU', 'Test Qualifier', '6', '~'),
  ('TQU', 'Test Qualifier', '7', 'Very High'),
  ('TQU', 'Test Qualifier', '8', 'High'),
  ('TQU', 'Test Qualifier', '9', 'Normal'),
  ('TQU', 'Test Qualifier', '10', 'Low'),
  ('TQU', 'Test Qualifier', '11', 'Very Low'),
  ('TQU', 'Test Qualifier', '12', 'Abnormal'),
  ('TQU', 'Test Qualifier', '13', 'Potential Abnormal'),
  ('TQU', 'Test Qualifier', '14', 'Outside ref range'),
  ('TQU', 'Test Qualifier', '15', 'Nil'),
  ('TQU', 'Test Qualifier', '16', 'Trace'),
  ('TQU', 'Test Qualifier', '17', '+'),
  ('TQU', 'Test Qualifier', '18', '++'),
  ('TQU', 'Test Qualifier', '19', '+++'),
  ('TQU', 'Test Qualifier', '20', 'Not examined'),
  ('TQU', 'Test Qualifier', '21', 'Positive'),
  ('TQU', 'Test Qualifier', '22', 'Negative'),
  ('TQU', 'Test Qualifier', '23', 'Absent'),
  ('TQU', 'Test Qualifier', '24', 'Present'),
  ('TQU', 'Test Qualifier', '25', 'Normal'),
  ('TQU', 'Test Qualifier', '26', 'Abnormal'),
  ('TQU', 'Test Qualifier', '27', 'Potential Abnormal'),
  ('TQU', 'Test Qualifier', '28', ''),
  ('TQU', 'Test Qualifier', '29', 'Negative'),
  ('TQU', 'Test Qualifier', '30', 'Positive'),
  ('TQU', 'Test Qualifier', '31', 'Positive'),
  ('TQU', 'Test Qualifier', '32', 'Negative'),
  ('TQU', 'Test Qualifier', '33', 'Unknown'),
  ('TQU', 'Test Qualifier', '34', 'Not examined'),
  ('TQU', 'Test Qualifier', '35', 'Above high reference limit'),
  ('TQU', 'Test Qualifier', '36', 'Below low reference limit'),
  ('TQU', 'Test Qualifier', '37', 'Outside reference range'),
  ('TQU', 'Test Qualifier', '38', 'Potentially abnormal'),
  ('TQU', 'Test Qualifier', '39', 'Normal'),
  ('TQU', 'Test Qualifier', '40', 'Low'),
  ('TQU', 'Test Qualifier', '41', 'High'),
  ('TQU', 'Test Qualifier', '42', 'Significantly Low'),
  ('TQU', 'Test Qualifier', '43', 'Significantly High'),
  ('TQU', 'Test Qualifier', '44', 'Abnormal'),
  ('TQU', 'Test Qualifier', '45', 'Very Abnormal'),
  ('TQU', 'Test Qualifier', '46', 'Not Applicable'),
  ('TRA', 'Transfer Out Reason', '0', 'Data Not Entered'),
  ('TRA', 'Transfer Out Reason', '1', 'Death'),
  ('TRA', 'Transfer Out Reason', '2', 'Removal to new TP/HB/CSA'),
  ('TRA', 'Transfer Out Reason', '3', 'Internal Transfer'),
  ('TRA', 'Transfer Out Reason', '4', 'Mental Hospital'),
  ('TRA', 'Transfer Out Reason', '5', 'Embarkation'),
  ('TRA', 'Transfer Out Reason', '6', 'New TP/HB/CSA/Same GP'),
  ('TRA', 'Transfer Out Reason', '7', 'Adopted Child'),
  ('TRA', 'Transfer Out Reason', '8', 'Services'),
  ('TRA', 'Transfer Out Reason', '9', 'Deduction at GP''s Request'),
  ('TRA', 'Transfer Out Reason', '10', 'Registration Cancelled'),
  ('TRA', 'Transfer Out Reason', '11', 'Service Dependant'),
  ('TRA', 'Transfer Out Reason', '12', 'Deduction at Patient''s Request'),
  ('TRA', 'Transfer Out Reason', '13', 'Other reason'),
  ('TRA', 'Transfer Out Reason', '14', 'Enlistment'),
  ('TRA', 'Transfer Out Reason', '15', 'Institution'),
  ('TRA', 'Transfer Out Reason', '16', 'Transfer within Practice'),
  ('TRA', 'Transfer Out Reason', '17', 'Linkage'),
  ('TRA', 'Transfer Out Reason', '18', 'Untraced - Miscellaneous'),
  ('TRA', 'Transfer Out Reason', '19', 'Untraced - Immig'),
  ('TRA', 'Transfer Out Reason', '20', 'Untraced - GP Resign'),
  ('TRA', 'Transfer Out Reason', '21', 'Untraced - College'),
  ('TRA', 'Transfer Out Reason', '22', 'Untraced - outwith Practice'),
  ('TRA', 'Transfer Out Reason', '23', 'Untraced - outwith HB'),
  ('TRA', 'Transfer Out Reason', '24', 'Multiple Transfer'),
  ('TRA', 'Transfer Out Reason', '25', 'Intra-consortium transfer'),
  ('TRA', 'Transfer Out Reason', '26', 'Returned Undelivered'),
  ('TRA', 'Transfer Out Reason', '27', 'Internal Transfer - Address Change'),
  ('TRA', 'Transfer Out Reason', '28', 'Internal Transfer within Partnership'),
  ('TRA', 'Transfer Out Reason', '29', 'Correspondence states ''gone away'''),
  ('TRA', 'Transfer Out Reason', '30', 'Practice advise outside their area'),
  ('TRA', 'Transfer Out Reason', '31', 'Practice advise patient no longer resident'),
  ('TRA', 'Transfer Out Reason', '32', 'Practice advise removal via screening system'),
  ('TRA', 'Transfer Out Reason', '33', 'Practice advise removal via vaccination data'),
  ('TRA', 'Transfer Out Reason', '34', 'Removal from Residential Institute'),
  ('TYP', 'Check Up Type', '0', 'Data Not Entered'),
  ('TYP', 'Check Up Type', '1', 'Acute'),
  ('TYP', 'Check Up Type', '2', 'Annual'),
  ('TYP', 'Check Up Type', '3', 'Routine'),
  ('URG', 'Urgency', '0', 'Data Not Entered'),
  ('URG', 'Urgency', '1', '2 week Wait'),
  ('URG', 'Urgency', '2', 'Routine'),
  ('URG', 'Urgency', '3', 'Stat (immediately)'),
  ('URG', 'Urgency', '4', 'Urgent'),
  ('URG', 'Urgency', '5', 'Emergency'),
  ('URG', 'Urgency', '6', 'Red Flag'),
  ('VIS', 'Visual Acuity', '0', 'Data Not Entered'),
  ('VIS', 'Visual Acuity', '1', '6/5'),
  ('VIS', 'Visual Acuity', '2', '6/6'),
  ('VIS', 'Visual Acuity', '3', '6/9'),
  ('VIS', 'Visual Acuity', '4', '6/12'),
  ('VIS', 'Visual Acuity', '5', '6/18'),
  ('VIS', 'Visual Acuity', '6', '6/24'),
  ('VIS', 'Visual Acuity', '7', '6/60'),
  ('VIS', 'Visual Acuity', '8', 'Count fingers'),
  ('VIS', 'Visual Acuity', '9', 'Follow hand movements'),
  ('VIS', 'Visual Acuity', '10', 'Perceives light'),
  ('VIS', 'Visual Acuity', '11', 'No perception of light'),
  ('VIS', 'Visual Acuity', '12', '6/36'),
  ('VIS', 'Visual Acuity', '13', '6/4'),
  ('VIS', 'Visual Acuity', '14', '6/7'),
  ('Y_N', 'Yes/no Flag', '0', 'Data Not Entered'),
  ('Y_N', 'Yes/no Flag', '1', 'Yes'),
  ('Y_N', 'Yes/no Flag', '2', 'No'),
  ('YND', 'Smoke/drink Status', '0', 'Data Not Entered'),
  ('YND', 'Smoke/drink Status', '1', 'Yes'),
  ('YND', 'Smoke/drink Status', '2', 'No'),
  ('YND', 'Smoke/drink Status', '3', 'Ex');